# Use Node 22 as base image
FROM node:22

WORKDIR /app

COPY package*.json ./

# Install all dependencies including devDependencies
RUN npm install --include=dev

COPY . .

# Build TypeScript
RUN npm run build

EXPOSE 5100

CMD ["npm", "run", "dev"]
