FROM python:3.10-slim

# Install OCR dependencies
RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    libtesseract-dev \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy project files
COPY requirements.txt .
COPY app/ ./app/

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt



# Expose port
EXPOSE 5200

# Run as module
CMD ["python", "-m", "app.main"]
