# Use Node 22 as base image
FROM node:22

# Set working directory inside container
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./

# Install all dependencies including TypeScript (devDependencies)
RUN npm install

# Copy all source code (including tsconfig, src, etc.)
COPY . .

# Build TypeScript project
RUN npm run build

# Expose the backend port
EXPOSE 5100

# Start the compiled backend
CMD ["npm", "run" , "dev"]
